# Hungarian translation of update-manager
# This file is distributed under the same license as the update-manager package.
# Copyright (C) 2005, Free Software Foundation, Inc.
# Gabor Kelemen <kelemeng@gnome.hu>, 2005.
#
#: ../DistUpgrade/DistUpgradeController.py:1075
msgid ""
msgstr ""
"Project-Id-Version: update-manager.HEAD\n"
"Report-Msgid-Bugs-To: sebastian.heinlein@web.de\n"
"POT-Creation-Date: 2020-08-03 09:26-0700\n"
"PO-Revision-Date: 2019-06-18 17:54+0000\n"
"Last-Translator: Báthory Péter <bathory86p@gmail.com>\n"
"Language-Team: Hungarian <gnome@gnome.hu>\n"
"Language: hu\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=n != 1;\n"
"X-Launchpad-Export-Date: 2019-11-15 04:47+0000\n"
"X-Generator: Launchpad (build c597c3229eb023b1e626162d5947141bf7befb13)\n"

#. TRANSLATORS: %s is a country
#: ../DistUpgrade/distro.py:215 ../DistUpgrade/distro.py:446
#, python-format
msgid "Server for %s"
msgstr "Kiszolgáló a következőhöz: %s"

#. More than one server is used. Since we don't handle this case
#. in the user interface we set "custom servers" to true and
#. append a list of all used servers
#: ../DistUpgrade/distro.py:233 ../DistUpgrade/distro.py:239
#: ../DistUpgrade/distro.py:255
msgid "Main server"
msgstr "Fő kiszolgáló"

#: ../DistUpgrade/distro.py:259
msgid "Custom servers"
msgstr "Egyéni kiszolgálók"

#: ../DistUpgrade/DistUpgradeAptCdrom.py:151
msgid "Could not calculate sources.list entry"
msgstr "Nem határozható meg a sources.list bejegyzés"

#: ../DistUpgrade/DistUpgradeAptCdrom.py:260
msgid ""
"Unable to locate any package files, perhaps this is not a Ubuntu Disc or the "
"wrong architecture?"
msgstr ""
"Egyetlen csomagfájl sem található! Lehet, hogy nem Ubuntu lemezt, vagy más "
"architektúrához tartozót helyezett a meghajtóba."

#: ../DistUpgrade/DistUpgradeAptCdrom.py:310
msgid "Failed to add the CD"
msgstr "A CD hozzáadása meghiúsult"

#: ../DistUpgrade/DistUpgradeAptCdrom.py:311
#, python-format
msgid ""
"There was a error adding the CD, the upgrade will abort. Please report this "
"as a bug if this is a valid Ubuntu CD.\n"
"\n"
"The error message was:\n"
"'%s'"
msgstr ""
"Hiba történt a CD hozzáadása során, a frissítés félbeszakad. Jelentse ezt "
"hibaként, ha ez egy érvényes Ubuntu CD.\n"
"\n"
"A hibaüzenet:\n"
"„%s”"

#: ../DistUpgrade/DistUpgradeCache.py:182
msgid "Remove package in bad state"
msgid_plural "Remove packages in bad state"
msgstr[0] "Hibás állapotban levő csomag eltávolítása"
msgstr[1] "Hibás állapotban levő csomagok eltávolítása"

#: ../DistUpgrade/DistUpgradeCache.py:185
#, python-format
msgid ""
"The package '%s' is in an inconsistent state and needs to be reinstalled, "
"but no archive can be found for it. Do you want to remove this package now "
"to continue?"
msgid_plural ""
"The packages '%s' are in an inconsistent state and need to be reinstalled, "
"but no archives can be found for them. Do you want to remove these packages "
"now to continue?"
msgstr[0] ""
"A(z) „%s” nevű csomag hibás! Újratelepítése szükséges, azonban nem található "
"hozzá megfelelő archívum. El kívánja távolítani ezt a csomagot a "
"folytatáshoz?"
msgstr[1] ""
"A(z) „%s” nevű csomagok hibásak! Újratelepítésük szükséges, azonban nem "
"található hozzájuk megfelelő archívum. El kívánja távolítani ezeket a "
"csomagokat a folytatáshoz?"

#. FIXME: not ideal error message, but we just reuse a
#. existing one here to avoid a new string
#: ../DistUpgrade/DistUpgradeCache.py:301
msgid "The server may be overloaded"
msgstr "Lehet, hogy a kiszolgáló túlterhelt"

#: ../DistUpgrade/DistUpgradeCache.py:414
msgid "Broken packages"
msgstr "Törött csomagok"

#: ../DistUpgrade/DistUpgradeCache.py:415
msgid ""
"Your system contains broken packages that couldn't be fixed with this "
"software. Please fix them first using synaptic or apt-get before proceeding."
msgstr ""
"A rendszere törött csomagokat tartalmaz, amelyek ezzel az alkalmazással nem "
"javíthatóak. Kérem, először javítsa ki őket a synaptic vagy az apt-get "
"segítségével."

#: ../DistUpgrade/DistUpgradeCache.py:660
#, fuzzy, python-format
msgid "Broken packages after upgrade: %s"
msgstr "Törött csomagok"

#. the most likely problem is the 3rd party pkgs so don't address
#. foreignPkgs and devRelease being True
#: ../DistUpgrade/DistUpgradeCache.py:669
msgid ""
"An unresolvable problem occurred while calculating the upgrade.\n"
"\n"
" "
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:672
msgid ""
"This was likely caused by:\n"
" * Unofficial software packages not provided by Ubuntu\n"
"Please use the tool 'ppa-purge' from the ppa-purge \n"
"package to remove software from a Launchpad PPA and \n"
"try the upgrade again.\n"
"\n"
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:680
msgid ""
"This was caused by:\n"
" * Upgrading to a pre-release version of Ubuntu\n"
"This is most likely a transient problem, \n"
"please try again later.\n"
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:687
msgid "This is most likely a transient problem, please try again later."
msgstr "Ez valószínűleg átmeneti probléma, próbálkozzon később."

#: ../DistUpgrade/DistUpgradeCache.py:690
msgid ""
"If none of this applies, then please report this bug using the command "
"'ubuntu-bug ubuntu-release-upgrader-core' in a terminal. "
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:692
msgid ""
"If you want to investigate this yourself the log files in '/var/log/dist-"
"upgrade' will contain details about the upgrade. Specifically, look at 'main."
"log' and 'apt.log'."
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:698
msgid "Could not calculate the upgrade"
msgstr "A frissítés előkészítése sikertelen"

#: ../DistUpgrade/DistUpgradeCache.py:757
msgid "Error authenticating some packages"
msgstr "Hiba történt néhány csomag hitelesítése közben"

#: ../DistUpgrade/DistUpgradeCache.py:758
msgid ""
"It was not possible to authenticate some packages. This may be a transient "
"network problem. You may want to try again later. See below for a list of "
"unauthenticated packages."
msgstr ""
"Néhány csomagot nem sikerült hitelesíteni. Lehetséges, hogy ezt átmeneti "
"hálózati probléma okozza, ezért érdemes később újra megpróbálni. Az alábbi "
"felsorolás a hitelesíthetetlen csomagokat tartalmazza."

#: ../DistUpgrade/DistUpgradeCache.py:779
#, python-format
msgid ""
"The package '%s' is marked for removal but it is in the removal blacklist."
msgstr ""
"A(z) „%s” nevű csomagot eltávolításra jelölte ki, de ez rajta van az "
"eltávolítási feketelistán."

#: ../DistUpgrade/DistUpgradeCache.py:785
#, python-format
msgid "The essential package '%s' is marked for removal."
msgstr "A létfontosságú „%s” csomagot eltávolításra jelölte ki."

#: ../DistUpgrade/DistUpgradeCache.py:794
#, python-format
msgid "Trying to install blacklisted version '%s'"
msgstr "Kísérlet a feketelistára tett „%s” verzió telepítésére"

#: ../DistUpgrade/DistUpgradeCache.py:916
#, python-format
msgid "Can't install '%s'"
msgstr "„%s” nem telepíthető"

#: ../DistUpgrade/DistUpgradeCache.py:917
msgid ""
"It was impossible to install a required package. Please report this as a bug "
"using 'ubuntu-bug ubuntu-release-upgrader-core' in a terminal."
msgstr ""
"Az igényelt csomag telepítése lehetetlen volt. Jelentse ezt a hibát a "
"terminálban kiadott „ubuntu-bug ubuntu-release-upgrader-core” paranccsal."

#: ../DistUpgrade/DistUpgradeCache.py:928
msgid "Can't guess meta-package"
msgstr "A meta-csomag megállapítása sikertelen"

#: ../DistUpgrade/DistUpgradeCache.py:929
#, python-format
msgid ""
"Your system does not contain a %s or %s package and it was not possible to "
"detect which version of Ubuntu you are running.\n"
" Please install one of the packages above first using synaptic or apt-get "
"before proceeding."
msgstr ""
"A rendszer nem tartalmazza a(z) %s vagy %s csomagok egyikét sem, és nem "
"tudta érzékelni, hogy melyik Ubuntu verziót futtatja.\n"
"Telepítse először az egyik fenti csomagot a synaptic vagy az apt-get "
"használatával a folytatás előtt."

#: ../DistUpgrade/DistUpgradeController.py:113
msgid "Reading cache"
msgstr "Gyorsítótár beolvasása"

#: ../DistUpgrade/DistUpgradeController.py:225
msgid "Unable to get exclusive lock"
msgstr "A kizárolagos zárolás nem lehetséges"

#: ../DistUpgrade/DistUpgradeController.py:226
msgid ""
"This usually means that another package management application (like apt-get "
"or aptitude) already running. Please close that application first."
msgstr ""
"Ez általában azt jelenti, hogy már fut egy másik csomagkezelő alkalmazás "
"(például apt-get vagy aptitude). Kérem először zárja be azt az alkalmazást."

#: ../DistUpgrade/DistUpgradeController.py:284
msgid "Upgrading over remote connection not supported"
msgstr "A frissítés nem támogatott távoli kapcsolaton keresztül"

#: ../DistUpgrade/DistUpgradeController.py:285
msgid ""
"You are running the upgrade over a remote ssh connection with a frontend "
"that does not support this. Please try a text mode upgrade with 'do-release-"
"upgrade'.\n"
"\n"
"The upgrade will abort now. Please try without ssh."
msgstr ""
"Távoli SSH-kapcsolaton keresztül futtatja a frissítést olyan felület "
"használatával, amely nem támogatja ezt. Próbálja meg szöveges módban "
"végrehajtani a frissítést a „do-release-upgrade” parancs segítségével.\n"
"\n"
"A frissítés most megszakad. Próbálja SSH nélkül."

#: ../DistUpgrade/DistUpgradeController.py:299
msgid "Continue running under SSH?"
msgstr "Folytatja a futtatást SSH alatt?"

#: ../DistUpgrade/DistUpgradeController.py:300
#, python-format
msgid ""
"This session appears to be running under ssh. It is not recommended to "
"perform a upgrade over ssh currently because in case of failure it is harder "
"to recover.\n"
"\n"
"If you continue, an additional ssh daemon will be started at port '%s'.\n"
"Do you want to continue?"
msgstr ""
"Úgy tűnik, ez a munkamenet SSH alatt fut. Jelenleg nem ajánlott, hogy SSH "
"kapcsolaton keresztül hajtsa végre a frissítést, ugyanis hiba esetén így "
"nehezebb a helyreállítás.\n"
"\n"
"Ha folytatja, egy újabb SSH-démon indul az alábbi porton: %s.\n"
"Szeretné folytatni?"

#: ../DistUpgrade/DistUpgradeController.py:314
msgid "Starting additional sshd"
msgstr "Új sshd indítása"

#: ../DistUpgrade/DistUpgradeController.py:315
#, python-format
msgid ""
"To make recovery in case of failure easier, an additional sshd will be "
"started on port '%s'. If anything goes wrong with the running ssh you can "
"still connect to the additional one.\n"
msgstr ""
"A hiba esetén történő helyreállítás megkönnyítése érdekében egy újabb sshd "
"indul a(z) %s porton. Ha bármiféle probléma lép fel az aktuális SSH futása "
"során, Ön továbbra is kapcsolódni tud majd a másik segítségével.\n"

#: ../DistUpgrade/DistUpgradeController.py:323
#, python-format
msgid ""
"If you run a firewall, you may need to temporarily open this port. As this "
"is potentially dangerous it's not done automatically. You can open the port "
"with e.g.:\n"
"'%s'"
msgstr ""
"Ha tűzfalat használ, akkor lehetséges, hogy ideiglenesen szükséges megnyitni "
"ezt a portot. Mivel a port megnyitása  lehetséges veszélyforrás, nem "
"történik automatikusan. A port megnyitható például a következő módon:\n"
"„%s”"

#: ../DistUpgrade/DistUpgradeController.py:401
#: ../DistUpgrade/DistUpgradeController.py:425
msgid "Can not upgrade"
msgstr "Nem lehet frissíteni"

#: ../DistUpgrade/DistUpgradeController.py:402
#, python-format
msgid "An upgrade from '%s' to '%s' is not supported with this tool."
msgstr ""
"Ez az eszköz nem támogatja a frissítést „%s” rendszerről „%s” rendszerre."

#: ../DistUpgrade/DistUpgradeController.py:426
msgid ""
"Your python3 install is corrupted. Please fix the '/usr/bin/python3' symlink."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:455
#, python-format
msgid "Can not write to '%s'"
msgstr "%s nem írható"

#: ../DistUpgrade/DistUpgradeController.py:456
#, python-format
msgid ""
"Its not possible to write to the system directory '%s' on your system. The "
"upgrade can not continue.\n"
"Please make sure that the system directory is writable."
msgstr ""
"A(z) „%s” rendszerkönyvtár nem írható. A frissítés nem folytatódhat.\n"
"Biztosítsa a rendszerkönyvtár írhatóságát."

#: ../DistUpgrade/DistUpgradeController.py:467
msgid "Include latest updates from the Internet?"
msgstr "Használja az interneten elérhető legújabb frissítéseket?"

#: ../DistUpgrade/DistUpgradeController.py:468
msgid ""
"The upgrade system can use the internet to automatically download the latest "
"updates and install them during the upgrade.  If you have a network "
"connection this is highly recommended.\n"
"\n"
"The upgrade will take longer, but when it is complete, your system will be "
"fully up to date.  You can choose not to do this, but you should install the "
"latest updates soon after upgrading.\n"
"If you answer 'no' here, the network is not used at all."
msgstr ""
"A frissítőrendszer használhatja az internetet a legújabb frissítések "
"letöltéséhez és telepítheti azokat a frissítés közben. Ha rendelkezik "
"internetkapcsolattal, ez a beállítás erősen ajánlott.\n"
"\n"
"A frissítés hosszabb ideig is eltarthat, a folyamat végeztével a rendszere "
"teljesen naprakész lesz. Választhatja e funkció mellőzését is, azonban "
"ajánlott a legújabb frissítések telepítését elvégezni a rendszerfrissítés "
"után nem sokkal.\n"
"Ha a „Nem”-et választja, a telepítő nem fogja használni internetkapcsolatát."

#: ../DistUpgrade/DistUpgradeController.py:646
#, python-format
msgid "Not for humans during development stage of release %s"
msgstr "%s erősen kísérleti, nem embernek való kiadása :)"

#: ../DistUpgrade/DistUpgradeController.py:747
#, python-format
msgid "disabled on upgrade to %s"
msgstr "letiltva a(z) %s változatra frissítéskor"

#: ../DistUpgrade/DistUpgradeController.py:804
msgid "No valid sources.list entry found"
msgstr "Nem található érvényes sources.list bejegyzés"

#: ../DistUpgrade/DistUpgradeController.py:805
#, python-format
msgid ""
"While scanning your repository information no entry about %s could be "
"found.\n"
"\n"
"An upgrade might not succeed.\n"
"\n"
"Do you want to continue anyway?"
msgstr ""
"A tárolóinformációk vizsgálatakor nem volt bejegyzés található erről: %s.\n"
"\n"
"A frissítés lehet, hogy sikertelen lesz.\n"
"\n"
"Mindenképp folytatja?"

#: ../DistUpgrade/DistUpgradeController.py:817
msgid "No valid mirror found"
msgstr "Nem található érvényes tükör"

#: ../DistUpgrade/DistUpgradeController.py:818
#, python-format
msgid ""
"While scanning your repository information no mirror entry for the upgrade "
"was found. This can happen if you run an internal mirror or if the mirror "
"information is out of date.\n"
"\n"
"Do you want to rewrite your 'sources.list' file anyway? If you choose 'Yes' "
"here it will update all '%s' to '%s' entries.\n"
"If you select 'No' the upgrade will cancel."
msgstr ""
"A tárolóinformációk lekérdezése során a frissítéshez nem található tükör "
"bejegyzés. Ez akkor lehetséges, ha belső tükröt használ, vagy a "
"tükörinformációk elavultak.\n"
"\n"
"Mindenképpen újra szeretné írni a „sources.list” fájlt? Ha itt az „Igen”-t "
"választja, akkor minden „%s” bejegyzés megváltozik erre: „%s”.\n"
"Ha a „Nem”-et választja, a frissítés megszakad."

#. hm, still nothing useful ...
#: ../DistUpgrade/DistUpgradeController.py:838
msgid "Generate default sources?"
msgstr "Alapértelmezett források ismételt előállítása?"

#: ../DistUpgrade/DistUpgradeController.py:839
#, python-format
msgid ""
"After scanning your 'sources.list' no valid entry for '%s' was found.\n"
"\n"
"Should default entries for '%s' be added? If you select 'No', the upgrade "
"will cancel."
msgstr ""
"A „sources.list” átnézése után sem található érvényes bejegyzés a "
"következőről: %s.\n"
"\n"
"Hozzáadja az alap bejegyzéseket a következőhöz: „%s”? A „Nem” kiválasztása "
"megszakítja a frissítést."

#: ../DistUpgrade/DistUpgradeController.py:874
#: ../DistUpgrade/DistUpgradeController.py:880
msgid "Repository information invalid"
msgstr "Érvénytelen tárolóinformációk"

#: ../DistUpgrade/DistUpgradeController.py:875
msgid ""
"Upgrading the repository information resulted in a invalid file so a bug "
"reporting process is being started."
msgstr ""
"A tároló frissítése érvénytelen fájlt eredményezett, ezért most elindul egy "
"hibajelentési folyamat."

#: ../DistUpgrade/DistUpgradeController.py:881
msgid ""
"Upgrading the repository information resulted in a invalid file. To report a "
"bug install apport and then execute 'apport-bug ubuntu-release-upgrader'."
msgstr ""
"A tárolóinformációk frissítés érvénytelen fájlt eredményezett. Hiba "
"jelentéséhez telepítse az apport csomagot, és adja ki az „apport-bug ubuntu-"
"release-upgrader” parancsot."

#: ../DistUpgrade/DistUpgradeController.py:890
msgid "Third party sources disabled"
msgstr "A külső források letiltva"

#: ../DistUpgrade/DistUpgradeController.py:891
msgid ""
"Some third party entries in your sources.list were disabled. You can re-"
"enable them after the upgrade with the 'software-properties' tool or your "
"package manager."
msgstr ""
"A sources.list néhány harmadik féltől származó forrása le lett tiltva. A "
"frissítés után újraengedélyezheti őket a Szoftverforrások eszközzel, vagy a "
"csomagkezelővel."

#: ../DistUpgrade/DistUpgradeController.py:933
msgid "Package in inconsistent state"
msgid_plural "Packages in inconsistent state"
msgstr[0] "Nem konzisztens állapotú csomag"
msgstr[1] "Nem konzisztens állapotú csomagok"

#: ../DistUpgrade/DistUpgradeController.py:936
#, python-format
msgid ""
"The package '%s' is in an inconsistent state and needs to be reinstalled, "
"but no archive can be found for it. Please reinstall the package manually or "
"remove it from the system."
msgid_plural ""
"The packages '%s' are in an inconsistent state and need to be reinstalled, "
"but no archive can be found for them. Please reinstall the packages manually "
"or remove them from the system."
msgstr[0] ""
"A(z) „%s” nevű csomag hibás! Újratelepítése szükséges, azonban nem található "
"hozzá megfelelő archívum. Telepítse újra a csomagot saját kezűleg, vagy "
"távolítsa el a rendszerről."
msgstr[1] ""
"A(z) „%s” nevű csomagok hibásak! Újratelepítésük szükséges, azonban nem "
"található hozzájuk megfelelő archívum. Telepítse újra a csomagot saját "
"kezűleg, vagy távolítsa el a rendszerről."

#: ../DistUpgrade/DistUpgradeController.py:999
msgid "Error during update"
msgstr "Hiba történt a frissítés közben"

#: ../DistUpgrade/DistUpgradeController.py:1000
msgid ""
"A problem occurred during the update. This is usually some sort of network "
"problem, please check your network connection and retry."
msgstr ""
"Hiba lépett fel a frissítés közben. Ez többnyire hálózati problémára utal. "
"Kérem, ellenőrizze a hálózati kapcsolatot és próbálja újra."

#: ../DistUpgrade/DistUpgradeController.py:1043
#: ../DistUpgrade/DistUpgradeController.py:1048
msgid "EFI System Partition (ESP) not usable"
msgstr "Az EFI rendszerpartíció (ESP) nem használható"

#: ../DistUpgrade/DistUpgradeController.py:1044
msgid ""
"Your EFI System Partition (ESP) is not mounted at /boot/efi. Please ensure "
"that it is properly configured and try again."
msgstr ""
"Az EFI rendszerpartíció (ESP) nem a /boot/efi alá van csatolva. Győződjön "
"meg róla, hogy megfelelően van beállítva, és próbálja újra."

#: ../DistUpgrade/DistUpgradeController.py:1049
msgid ""
"The EFI System Partition (ESP) mounted at /boot/efi is not writable. Please "
"mount this partition read-write and try again."
msgstr ""
"A /boot/efi alá csatolt EFI rendszerpartíció (ESP) nem írható. Csatolja a "
"partíciót írható-olvasható módban, és próbálja újra."

#: ../DistUpgrade/DistUpgradeController.py:1056
msgid "Not enough free disk space"
msgstr "Nincs elég szabad hely a merevlemezen"

#. TRANSLATORS: you can change the order of the sentence,
#. make sure to keep all {str_*} string untranslated.
#: ../DistUpgrade/DistUpgradeController.py:1059
#, python-brace-format
msgid ""
"The upgrade has aborted. The upgrade needs a total of {str_total} free space "
"on disk '{str_dir}'. Please free at least an additional {str_needed} of disk "
"space on '{str_dir}'. {str_remedy}"
msgstr ""
"A frissítés megszakadt. A frissítéshez összesen {str_total} szabad hely "
"szükséges a(z) „{str_dir}” lemezen. Szabadítson fel legalább még "
"{str_needed} lemezhelyet ezen: „{str_dir}”. {str_remedy}"

#. specific ways to resolve lack of free space
#: ../DistUpgrade/DistUpgradeController.py:1064
msgid ""
"Remove temporary packages of former installations using 'sudo apt clean'."
msgstr ""
"Távolítsa el korábbi telepítések ideiglenes csomagjait a „sudo apt clean” "
"használatával."

#: ../DistUpgrade/DistUpgradeController.py:1066
msgid ""
"You can remove old kernels using 'sudo apt autoremove' and you could also "
"set COMPRESS=xz in /etc/initramfs-tools/initramfs.conf to reduce the size of "
"your initramfs."
msgstr ""
"Eltávolíthatja a régi kerneleket a „sudo apt autoremove” használatával, és "
"megadhatja a COMPRESS=xz beállítást az /etc/initramfs-tools/initramfs.conf "
"fájlban az initramfs méretének csökkentéséhez."

#: ../DistUpgrade/DistUpgradeController.py:1071
msgid ""
"Empty your trash and remove temporary packages of former installations using "
"'sudo apt-get clean'."
msgstr ""
"Ürítse a kukát, és távolítsa el korábbi telepítések ideiglenes csomagjait a "
"„sudo apt clean” használatával."

#: ../DistUpgrade/DistUpgradeController.py:1074
msgid "Reboot to clean up files in /tmp."
msgstr "Indítsa újra a gépet a /tmp alatti fájlok törléséhez."

#. calc the dist-upgrade and see if the removals are ok/expected
#. do the dist-upgrade
#: ../DistUpgrade/DistUpgradeController.py:1113
#: ../DistUpgrade/DistUpgradeController.py:1989
#: ../DistUpgrade/DistUpgradeController.py:2039
msgid "Calculating the changes"
msgstr "Módosítások előkészítése"

#. ask the user
#: ../DistUpgrade/DistUpgradeController.py:1157
msgid "Do you want to start the upgrade?"
msgstr "Biztosan el szeretné kezdeni a frissítést?"

#: ../DistUpgrade/DistUpgradeController.py:1176
#, python-format
msgid ""
"Livepatch security updates are not available for Ubuntu %s. If you upgrade, "
"Livepatch will turn off."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1248
msgid "Upgrade canceled"
msgstr "Frissítés megszakítva"

#: ../DistUpgrade/DistUpgradeController.py:1249
msgid ""
"The upgrade will cancel now and the original system state will be restored. "
"You can resume the upgrade at a later time."
msgstr ""
"A frissítés visszavonásra kerül, és az eredeti rendszerállapot lesz "
"visszaállítva. A frissítést később lehet folytatni."

#: ../DistUpgrade/DistUpgradeController.py:1255
#: ../DistUpgrade/DistUpgradeController.py:1400
msgid "Could not download the upgrades"
msgstr "A frissítések nem tölthetők le"

#: ../DistUpgrade/DistUpgradeController.py:1256
msgid ""
"The upgrade has aborted. Please check your Internet connection or "
"installation media and try again. All files downloaded so far have been kept."
msgstr ""
"A frissítés félbeszakadt. Kérjük ellenőrizze internet kapcsolatát vagy a "
"telepítő adathordozót, és próbálja újra. Az eddig letöltött fájlok "
"megmaradnak."

#. FIXME: strings are not good, but we are in string freeze
#. currently
#: ../DistUpgrade/DistUpgradeController.py:1349
#: ../DistUpgrade/DistUpgradeController.py:1388
#: ../DistUpgrade/DistUpgradeController.py:1504
msgid "Error during commit"
msgstr "Hiba a módosítások rögzítése közben"

#. generate a new cache
#: ../DistUpgrade/DistUpgradeController.py:1351
#: ../DistUpgrade/DistUpgradeController.py:1390
#: ../DistUpgrade/DistUpgradeController.py:1543
msgid "Restoring original system state"
msgstr "A rendszer eredeti állapotának helyreállítása"

#: ../DistUpgrade/DistUpgradeController.py:1352
#: ../DistUpgrade/DistUpgradeController.py:1367
#: ../DistUpgrade/DistUpgradeController.py:1391
msgid "Could not install the upgrades"
msgstr "A frissítések nem telepíthetők"

#. invoke the frontend now and show a error message
#: ../DistUpgrade/DistUpgradeController.py:1357
msgid ""
"The upgrade has aborted. Your system could be in an unusable state. A "
"recovery will run now (dpkg --configure -a)."
msgstr ""
"A frissítés megszakadt. A rendszer használhatatlan állapotban lehet. A "
"helyreállítás azonnal indul (dpkg --configure -a)."

#: ../DistUpgrade/DistUpgradeController.py:1362
#, python-format
msgid ""
"\n"
"\n"
"Please report this bug in a browser at http://bugs.launchpad.net/ubuntu/"
"+source/ubuntu-release-upgrader/+filebug and attach the files in /var/log/"
"dist-upgrade/ to the bug report.\n"
"%s"
msgstr ""
"\n"
"\n"
"Jelentse ezt a hibát böngészőben a http://bugs.launchpad.net/ubuntu/+source/"
"ubuntu-release-upgrader/+filebug címre, és csatolja a fájlokat a /var/log/"
"dist-upgrade/ mappából.\n"
"%s"

#: ../DistUpgrade/DistUpgradeController.py:1401
msgid ""
"The upgrade has aborted. Please check your Internet connection or "
"installation media and try again. "
msgstr ""
"A frissítés megszakadt. Ellenőrizze az internetkapcsolatát vagy a telepítési "
"adathordozót, és próbálja újra. "

#: ../DistUpgrade/DistUpgradeController.py:1429
msgid "Searching for obsolete software"
msgstr "Elavult szoftverek keresése"

#: ../DistUpgrade/DistUpgradeController.py:1492
msgid "Remove obsolete packages?"
msgstr "Eltávolítja az elavult csomagokat?"

#: ../DistUpgrade/DistUpgradeController.py:1493
#: ../data/gtkbuilder/DistUpgrade.ui.h:8
msgid "_Keep"
msgstr "_Megtartás"

#: ../DistUpgrade/DistUpgradeController.py:1493
msgid "_Remove"
msgstr "_Eltávolítás"

#: ../DistUpgrade/DistUpgradeController.py:1505
msgid ""
"A problem occurred during the clean-up. Please see the below message for "
"more information. "
msgstr ""
"A frissítés befejező fázisa közben hiba lépett fel. Az alábbi üzenet további "
"információkat tartalmaz a hibára vonatkozóan. "

#. FIXME: instead of error out, fetch and install it
#. here
#: ../DistUpgrade/DistUpgradeController.py:1581
msgid "Required depends is not installed"
msgstr "A szükséges függőségek nincsenek telepítve"

#: ../DistUpgrade/DistUpgradeController.py:1582
#, python-format
msgid "The required dependency '%s' is not installed. "
msgstr "A következő függőség nincs telepítve: %s. "

#. sanity check (check for ubuntu-desktop, brokenCache etc)
#. then open the cache (again)
#: ../DistUpgrade/DistUpgradeController.py:1849
#: ../DistUpgrade/DistUpgradeController.py:1939
msgid "Checking package manager"
msgstr "Csomagkezelő ellenőrzése"

#: ../DistUpgrade/DistUpgradeController.py:1855
#: ../DistUpgrade/DistUpgradeController.py:1861
msgid "Preparing the upgrade failed"
msgstr "A frissítés előkészítése meghiúsult"

#: ../DistUpgrade/DistUpgradeController.py:1856
msgid ""
"Preparing the system for the upgrade failed so a bug reporting process is "
"being started."
msgstr ""
"A rendszer előkészítése a frissítésre sikertelen, emiatt elindul egy "
"hibajelentési folyamat."

#: ../DistUpgrade/DistUpgradeController.py:1862
msgid ""
"Preparing the system for the upgrade failed. To report a bug install apport "
"and then execute 'apport-bug ubuntu-release-upgrader'."
msgstr ""
"A rendszer előkészítése a frissítésre meghiúsult.  Hiba jelentéséhez "
"telepítse az apport csomagot, és adja ki az „apport-bug ubuntu-release-"
"upgrader” parancsot."

#: ../DistUpgrade/DistUpgradeController.py:1879
#: ../DistUpgrade/DistUpgradeController.py:1889
msgid "Getting upgrade prerequisites failed"
msgstr "A frissítés előfeltételeinek lekérése meghiúsult"

#: ../DistUpgrade/DistUpgradeController.py:1880
msgid ""
"The system was unable to get the prerequisites for the upgrade. The upgrade "
"will abort now and restore the original system state.\n"
"\n"
"Additionally, a bug reporting process is being started."
msgstr ""
"A rendszer nem volt képes a frissítés előfeltételeinek lekérésére. A "
"frissítés ezért most megszakad, és a rendszer eredeti állapotába áll "
"vissza.\n"
"\n"
"Ezen kívül elindul egy hibajelentési folyamat is."

#: ../DistUpgrade/DistUpgradeController.py:1890
msgid ""
"The system was unable to get the prerequisites for the upgrade. The upgrade "
"will abort now and restore the original system state.\n"
"\n"
"To report a bug install apport and then execute 'apport-bug ubuntu-release-"
"upgrader'."
msgstr ""
"A rendszer nem tudta a frissítés előfeltételeit beszerezni. A frissítés most "
"megszakad, és helyreállítja az eredeti rendszerállapotot.\n"
"\n"
"Hiba jelentéséhez telepítse az apport csomagot, és adja ki az „apport-bug "
"ubuntu-release-upgrader” parancsot."

#: ../DistUpgrade/DistUpgradeController.py:1923
msgid "Updating repository information"
msgstr "Tárolóinformációk frissítése"

#: ../DistUpgrade/DistUpgradeController.py:1930
msgid "Failed to add the cdrom"
msgstr "Nem sikerült a CD-ROM hozzáadása"

#: ../DistUpgrade/DistUpgradeController.py:1931
msgid "Sorry, adding the cdrom was not successful."
msgstr "Elnézést, a CD-ROM hozzáadása sikertelen."

#: ../DistUpgrade/DistUpgradeController.py:1966
msgid "Invalid package information"
msgstr "Érvénytelen csomaginformációk"

#: ../DistUpgrade/DistUpgradeController.py:1967
#, python-format
msgid ""
"After updating your package information, the essential package '%s' could "
"not be located. This may be because you have no official mirrors listed in "
"your software sources, or because of excessive load on the mirror you are "
"using. See /etc/apt/sources.list for the current list of configured software "
"sources.\n"
"In the case of an overloaded mirror, you may want to try the upgrade again "
"later."
msgstr ""
"A csomaginformációk frissítése után a(z) „%s” alapvető csomag nem található. "
"Ez azért lehet, mert nem szerepelnek hivatalos tükörszerver a "
"szoftverforrások között, vagy az éppen használt tükörszerver túlterhelt. "
"Nézze meg a /etc/apt/sources.list fájlt a jelenleg konfigurált "
"szoftverforrások listájának megtekintéséhez.\n"
"Ha a tükörszerver túlterhelt, érdemes megpróbálni a frissítést később."

#: ../DistUpgrade/DistUpgradeController.py:1996
#: ../DistUpgrade/DistUpgradeController.py:2095
msgid "Fetching"
msgstr "Letöltés"

#: ../DistUpgrade/DistUpgradeController.py:2003
#: ../DistUpgrade/DistUpgradeController.py:2024
#: ../DistUpgrade/DistUpgradeController.py:2045
#: ../DistUpgrade/DistUpgradeController.py:2099
msgid "Upgrading"
msgstr "Frissítés"

#: ../DistUpgrade/DistUpgradeController.py:2005
msgid "Upgrade infeasible"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:2006
msgid ""
"The upgrade could not be completed, there were errors during the upgrade "
"process."
msgstr ""

#. don't abort here, because it would restore the sources.list
#: ../DistUpgrade/DistUpgradeController.py:2027
msgid "Upgrade incomplete"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:2028
msgid ""
"The upgrade has partially completed but there were errors during the upgrade "
"process."
msgstr ""

#. don't abort here, because it would restore the sources.list
#: ../DistUpgrade/DistUpgradeController.py:2050
#: ../DistUpgrade/DistUpgradeController.py:2101
#: ../DistUpgrade/DistUpgradeController.py:2107
#: ../DistUpgrade/DistUpgradeController.py:2118
msgid "Upgrade complete"
msgstr "A frissítés befejeződött"

#: ../DistUpgrade/DistUpgradeController.py:2051
#: ../DistUpgrade/DistUpgradeController.py:2102
#: ../DistUpgrade/DistUpgradeController.py:2108
msgid ""
"The upgrade has completed but there were errors during the upgrade process."
msgstr ""
"A frissítés befejeződött, de hibák történtek a frissítési folyamat alatt."

#: ../DistUpgrade/DistUpgradeController.py:2070
msgid "System upgrade is complete."
msgstr "A rendszer frissítése befejeződött."

#: ../DistUpgrade/DistUpgradeController.py:2119
msgid "The partial upgrade was completed."
msgstr "Az intelligens frissítés sikeresen befejeződött."

#: ../DistUpgrade/DistUpgradeController.py:2147
msgid "Lock screen disabled"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:2148
msgid ""
"Your lock screen has been disabled and will remain disabled until you reboot."
msgstr ""

#: ../DistUpgrade/DistUpgradeFetcher.py:107
#: ../DistUpgrade/DistUpgradeFetcherKDE.py:170
msgid "Could not find the release notes"
msgstr "Nem érhetők el a kiadási megjegyzések"

#: ../DistUpgrade/DistUpgradeFetcher.py:108
#: ../DistUpgrade/DistUpgradeFetcherKDE.py:171
msgid "The server may be overloaded. "
msgstr "A kiszolgáló túl lehet terhelve. "

#: ../DistUpgrade/DistUpgradeFetcher.py:120
#: ../DistUpgrade/DistUpgradeFetcherKDE.py:175
msgid "Could not download the release notes"
msgstr "A kiadási megjegyzések nem tölthetők le"

#: ../DistUpgrade/DistUpgradeFetcher.py:121
#: ../DistUpgrade/DistUpgradeFetcherKDE.py:176
msgid "Please check your internet connection."
msgstr "Kérjük ellenőrizze az internetkapcsolatát."

#: ../DistUpgrade/DistUpgradeFetcherCore.py:73
#, python-format
msgid "authenticate '%(file)s' against '%(signature)s' "
msgstr "„%(file)s” hitelesítése ezzel: „%(signature)s” "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:97
#, python-format
msgid "extracting '%s'"
msgstr "„%s” kicsomagolása"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:118
#: ../DistUpgrade/DistUpgradeFetcherCore.py:119
msgid "Could not run the upgrade tool"
msgstr "Nem sikerült futtatni a frissítőeszközt"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:120
msgid ""
"This is most likely a bug in the upgrade tool. Please report it as a bug "
"using the command 'ubuntu-bug ubuntu-release-upgrader-core'."
msgstr ""
"Ez valószínűleg egy hiba a frissítési eszközben. Jelentse a hibát az „ubuntu-"
"bug ubuntu-release-upgrader-core” paranccsal."

#: ../DistUpgrade/DistUpgradeFetcherCore.py:197
msgid "Upgrade tool signature"
msgstr "Frissítőeszköz aláírása"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:204
msgid "Upgrade tool"
msgstr "Frissítőeszköz"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:238
msgid "Failed to fetch"
msgstr "A letöltés meghiúsult"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:239
msgid "Fetching the upgrade failed. There may be a network problem. "
msgstr ""
"A frissítés letöltése meghiúsult. Lehetséges, hogy hálózati probléma áll "
"fenn. "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:243
msgid "Authentication failed"
msgstr "Hitelesítés sikertelen"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:244
msgid ""
"Authenticating the upgrade failed. There may be a problem with the network "
"or with the server. "
msgstr ""
"A frissítés hitelesítése meghiúsult. Probléma lehet a hálózattal vagy a "
"kiszolgálóval. "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:249
msgid "Failed to extract"
msgstr "A kibontás meghiúsult"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:250
msgid ""
"Extracting the upgrade failed. There may be a problem with the network or "
"with the server. "
msgstr ""
"A frissítés kibontása meghiúsult. Probléma lehet a hálózattal vagy a "
"kiszolgálóval. "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:255
msgid "Verification failed"
msgstr "Az ellenőrzés meghiúsult"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:256
msgid ""
"Verifying the upgrade failed.  There may be a problem with the network or "
"with the server. "
msgstr ""
"A frissítés ellenőrzése meghiúsult. Probléma lehet a hálózattal vagy a "
"kiszolgálóval. "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:270
#: ../DistUpgrade/DistUpgradeFetcherCore.py:276
msgid "Can not run the upgrade"
msgstr "A frissítés nem futtatható!"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:271
msgid ""
"This usually is caused by a system where /tmp is mounted noexec. Please "
"remount without noexec and run the upgrade again."
msgstr ""
"Ez a hiba általában akkor jön elő, ha a /tmp mappa noexec kapcsolóval van "
"felcsatolva. Kérjük csatolja újra noexec kapcsoló nélkül, majd próbálja "
"újból a frissítést."

#: ../DistUpgrade/DistUpgradeFetcherCore.py:277
#, python-format
msgid "The error message is '%s'."
msgstr "A hibaüzenet: „%s”."

#: ../DistUpgrade/DistUpgradeFetcherKDE.py:151
msgid "&Upgrade"
msgstr "&Frissítés"

#: ../DistUpgrade/DistUpgradeFetcherKDE.py:154
#: ../DistUpgrade/DistUpgradeViewKDE.py:715
msgid "&Cancel"
msgstr "&Mégse"

#: ../DistUpgrade/DistUpgradeFetcherKDE.py:156
#: ../data/gtkbuilder/ReleaseNotes.ui.h:1
msgid "Release Notes"
msgstr "Kiadási megjegyzések"

#: ../DistUpgrade/DistUpgradeFetcherKDE.py:191
msgid "Upgrade"
msgstr "Frissítés"

#: ../DistUpgrade/DistUpgradeFetcherKDE.py:207
#: ../DistUpgrade/DistUpgradeFetcherKDE.py:222
msgid "Downloading additional package files..."
msgstr "További csomagfájlok letöltése..."

#: ../DistUpgrade/DistUpgradeFetcherKDE.py:224
#, python-format
msgid "File %s of %s at %sB/s"
msgstr "%s. fájl, összesen %s. Sebesség: %sB/s"

#: ../DistUpgrade/DistUpgradeFetcherKDE.py:228
#, python-format
msgid "File %s of %s"
msgstr "%s. fájl, összesen %s."

#. print("mediaChange %s %s" % (medium, drive))
#: ../DistUpgrade/DistUpgradeFetcherKDE.py:235
#: ../DistUpgrade/DistUpgradeViewGtk3.py:125
#: ../DistUpgrade/DistUpgradeViewKDE.py:302
#, python-format
msgid "Please insert '%s' into the drive '%s'"
msgstr "Helyezze be a(z) „%s” adathordozót a(z) „%s” meghajtóba."

#: ../DistUpgrade/DistUpgradeFetcherKDE.py:237
#: ../DistUpgrade/DistUpgradeFetcherKDE.py:242
#: ../DistUpgrade/DistUpgradeFetcherKDE.py:243
#: ../DistUpgrade/DistUpgradeViewKDE.py:303
msgid "Media Change"
msgstr "Adathordozó-csere"

#: ../DistUpgrade/DistUpgradeQuirks.py:227
msgid "Your graphics hardware may not be fully supported in Ubuntu 14.04."
msgstr ""
"A videokártyája nem biztos, hogy megfelelően lesz támogatva az Ubuntu 14.04 "
"verziójában."

#: ../DistUpgrade/DistUpgradeQuirks.py:229
msgid ""
"Running the 'unity' desktop environment is not fully supported by your "
"graphics hardware. You will maybe end up in a very slow environment after "
"the upgrade. Our advice is to keep the LTS version for now. For more "
"information see https://wiki.ubuntu.com/X/Bugs/"
"UpdateManagerWarningForUnity3D Do you still want to continue with the "
"upgrade?"
msgstr ""
"Az Ön grafikus hardvere nem támogatja teljesen a „unity” asztali környezet "
"futtatását. Várhatóan a frissítés után nagyon lassú környezetet fog kapni. "
"Azt tanácsoljuk, most még tartsa meg az LTS változatot. További "
"információért látogassa meg a https://wiki.ubuntu.com/X/Bugs/"
"UpdateManagerWarningForUnity3D oldalt. Még így is szeretné folytatni a "
"frissítést?"

#: ../DistUpgrade/DistUpgradeQuirks.py:253
msgid "Your graphics hardware may not be fully supported in Ubuntu 12.04 LTS."
msgstr ""
"Videokártyája nem biztos, hogy teljesen támogatott lesz Ubuntu 12.04 LTS "
"alatt."

#: ../DistUpgrade/DistUpgradeQuirks.py:255
msgid ""
"The support in Ubuntu 12.04 LTS for your Intel graphics hardware is limited "
"and you may encounter problems after the upgrade. For more information see "
"https://wiki.ubuntu.com/X/Bugs/UpdateManagerWarningForI8xx Do you want to "
"continue with the upgrade?"
msgstr ""
"Az Ubuntu 12.04 LTS támogatása az Intel videokártyájához korlátozott, és "
"problémákba ütközhet a frissítés után. További információkért olvassa el a "
"https://wiki.ubuntu.com/X/Bugs/UpdateManagerWarningForI8xx oldalt. Folytatni "
"szeretné a frissítést?"

#: ../DistUpgrade/DistUpgradeQuirks.py:275
msgid ""
"Upgrading may reduce desktop effects, and performance in games and other "
"graphically intensive programs."
msgstr ""
"A frissítés visszafoghatja a vizuális effektusokat, a játékok és a sok "
"grafikai számítást igénylő alkalmazások teljesítményét."

#: ../DistUpgrade/DistUpgradeQuirks.py:279
msgid ""
"This computer is currently using the AMD 'fglrx' graphics driver. No version "
"of this driver is available that works with your hardware in Ubuntu 10.04 "
"LTS.\n"
"\n"
"Do you want to continue?"
msgstr ""
"Ez a számítógép jelenleg az AMD „fglrx” grafikus meghajtóját használja. "
"Ennek a meghajtónak nem érhető el a hardverét az Ubuntu 10.04 LTS alatt "
"kezelni képes verziója.\n"
"\n"
"Biztosan folytatja?"

#: ../DistUpgrade/DistUpgradeQuirks.py:318
msgid "Sorry, no more upgrades for this system"
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:319
#, python-format
msgid ""
"There will not be any further Ubuntu releases for this system's 'i386' "
"architecture.\n"
"\n"
"Updates for Ubuntu %s will continue until %s."
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:334
msgid "No ARMv6 CPU"
msgstr "Nem ARMv6 processzor"

#: ../DistUpgrade/DistUpgradeQuirks.py:335
msgid ""
"Your system uses an ARM CPU that is older than the ARMv6 architecture. All "
"packages in karmic were built with optimizations requiring ARMv6 as the "
"minimal architecture. It is not possible to upgrade your system to a new "
"Ubuntu release with this hardware."
msgstr ""
"A számítógépe ARMv6-nál régebbi ARM architektúrájú processzorral "
"rendelkezik. A Karmicban minden csomag legalább ARMv6-ot igénylő "
"optimalizációkkal készült. Ezen a hardveren nem frissíthető a rendszer új "
"Ubuntu kiadásra."

#: ../DistUpgrade/DistUpgradeQuirks.py:355
msgid "No init available"
msgstr "Nem érhető el init"

#: ../DistUpgrade/DistUpgradeQuirks.py:356
msgid ""
"Your system appears to be a virtualised environment without an init daemon, "
"e.g. Linux-VServer. Ubuntu 10.04 LTS cannot function within this type of "
"environment, requiring an update to your virtual machine configuration "
"first.\n"
"\n"
"Are you sure you want to continue?"
msgstr ""
"Úgy tűnik, hogy a rendszere egy virtualizált környezet init démon nélkül, "
"például Linux-VServer. Az Ubuntu 10.04 nem képes működni ebben a "
"környezetben, előbb frissítenie kell a virtuális gép beállításait.\n"
"\n"
"Biztosan folytatja?"

#: ../DistUpgrade/DistUpgradeQuirks.py:469
msgid "Connection to the Snap Store failed"
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:470
msgid ""
"You have the package lxd installed but your system is unable to reach the "
"Snap Store. lxd is now provided via a snap and the release upgrade will fail "
"if snapd is not functional. Please make sure you're connected to the "
"Internet and update any firewall or proxy settings as needed so that you can "
"reach api.snapcraft.io. If you are an enterprise with a firewall setup you "
"may want to configure a Snap Store proxy."
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:485
msgid "Connection to Snap Store failed"
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:486
msgid ""
"Your system does not have a connection to the Snap Store. For the best "
"upgrade experience make sure that your system can connect to api.snapcraft."
"io.\n"
"Do you still want to continue with the upgrade?"
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:495
msgid "Outdated snapd package"
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:496
msgid ""
"Your system does not have the latest version of snapd. Please update the "
"version of snapd on your system to improve the upgrade experience.\n"
"Do you still want to continue with the upgrade?"
msgstr ""

#. now perform direct API calls to the store, requesting size
#. information for each of the snaps needing installation
#: ../DistUpgrade/DistUpgradeQuirks.py:519
msgid "Calculating snap size requirements"
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:550
msgid "Processing snap replacements"
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:556
#, python-format
msgid "refreshing snap %s"
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:560
#, python-format
msgid "removing snap %s"
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:563
#, python-format
msgid "installing snap %s"
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:592
msgid "PAE not enabled"
msgstr "A PAE nincs bekapcsolva"

#: ../DistUpgrade/DistUpgradeQuirks.py:593
msgid ""
"Your system uses a CPU that does not have PAE enabled. Ubuntu only supports "
"non-PAE systems up to Ubuntu 12.04. To upgrade to a later version of Ubuntu, "
"you must enable PAE (if this is possible) see:\n"
"http://help.ubuntu.com/community/EnablingPAE"
msgstr ""
"A rendszere olyan processzort használ, amelyen a PAE nincs bekapcsolva. Az "
"Ubuntu csak az Ubuntu 12.04-ig támogatta a PAE nélküli rendszereket. Az "
"Ubuntu újabb verziójára frissítéshez be kell kapcsolnia a PAE-t (ha ez "
"lehetséges), lásd:  http://help.ubuntu.com/community/EnablingPAE"

#: ../DistUpgrade/DistUpgradeQuirks.py:916
msgid "Checking for installed snaps"
msgstr ""

#: ../DistUpgrade/DistUpgradeMain.py:58
msgid "Use the given path to search for a cdrom with upgradable packages"
msgstr ""
"A megadott útvonalat használja frissíthető csomagokat tartalmazó CD lemez "
"kereséséhez"

#: ../DistUpgrade/DistUpgradeMain.py:64
msgid ""
"Use frontend. Currently available: \n"
"DistUpgradeViewText, DistUpgradeViewGtk, DistUpgradeViewKDE"
msgstr ""
"Használja a kezelőfelületet. Jelenleg elérhető: \n"
"DistUpgradeViewText, DistUpgradeViewGtk, DistUpgradeViewKDE"

#: ../DistUpgrade/DistUpgradeMain.py:67
msgid "*DEPRECATED* this option will be ignored"
msgstr "*IDEJÉTMÚLT * ez az opció figyelmen kívül lesz hagyva"

#: ../DistUpgrade/DistUpgradeMain.py:70
msgid "Perform a partial upgrade only (no sources.list rewriting)"
msgstr ""
"Csak intelligens frissítés végrehajtása (nem írja újra a sources.list fájlt)"

#: ../DistUpgrade/DistUpgradeMain.py:73
msgid "Disable GNU screen support"
msgstr "GNU Screen támogatás kikapcsolása"

#: ../DistUpgrade/DistUpgradeMain.py:75
msgid "Set datadir"
msgstr "Adatkönyvtár beállítása"

#: ../DistUpgrade/DistUpgradeMain.py:78
msgid "Upgrade to the development release"
msgstr "Frissítés fejlesztési kiadásra"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:146
#: ../DistUpgrade/DistUpgradeViewKDE.py:316
msgid "Fetching is complete"
msgstr "A letöltés befejeződött"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:161
#: ../DistUpgrade/DistUpgradeViewKDE.py:332
#, python-format
msgid "Fetching file %li of %li at %sB/s"
msgstr "Fájl letöltése: %li / %li, (%sB/s)"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:163
#: ../DistUpgrade/DistUpgradeViewGtk3.py:325
#: ../DistUpgrade/DistUpgradeViewKDE.py:333
#: ../DistUpgrade/DistUpgradeViewKDE.py:483
#, python-format
msgid "About %s remaining"
msgstr "Kb. %s van hátra"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:166
#: ../DistUpgrade/DistUpgradeViewKDE.py:335
#, python-format
msgid "Fetching file %li of %li"
msgstr "%li. fájl letöltése (összesen: %li)"

#. FIXME: add support for the timeout
#. of the terminal (to display something useful then)
#. -> longer term, move this code into python-apt
#: ../DistUpgrade/DistUpgradeViewGtk3.py:198
#: ../DistUpgrade/DistUpgradeViewKDE.py:373
msgid "Applying changes"
msgstr "Módosítások alkalmazása"

#. we do not report followup errors from earlier failures
#: ../DistUpgrade/DistUpgradeViewGtk3.py:224
#: ../DistUpgrade/DistUpgradeViewKDE.py:386
msgid "dependency problems - leaving unconfigured"
msgstr "függőségi hibák - a csomag beállítatlan maradt"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:229
#: ../DistUpgrade/DistUpgradeViewKDE.py:388
#, python-format
msgid "Could not install '%s'"
msgstr "„%s” nem telepíthető"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:230
#: ../DistUpgrade/DistUpgradeViewKDE.py:389
#, python-format
msgid ""
"The upgrade will continue but the '%s' package may not be in a working "
"state. Please consider submitting a bug report about it."
msgstr ""
"A frissítés folytatódik, de a(z) „%s” csomag működésképtelen állapotban "
"lehet. Ezzel kapcsolatban küldjön be hibajelentést."

#. self.expander.set_expanded(True)
#: ../DistUpgrade/DistUpgradeViewGtk3.py:247
#: ../DistUpgrade/DistUpgradeViewKDE.py:411
#, python-format
msgid ""
"Replace the customized configuration file\n"
"'%s'?"
msgstr ""
"Lecseréli a személyre szabott\n"
"„%s”\n"
"konfigurációs fájlt?"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:248
#: ../DistUpgrade/DistUpgradeViewKDE.py:412
msgid ""
"You will lose any changes you have made to this configuration file if you "
"choose to replace it with a newer version."
msgstr ""
"A beállítófájl összes módosítása elvész, ha lecseréli az újabb verzióra."

#: ../DistUpgrade/DistUpgradeViewGtk3.py:268
#: ../DistUpgrade/DistUpgradeViewKDE.py:435
msgid "The 'diff' command was not found"
msgstr "A „diff” parancs nem található"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:535
#: ../DistUpgrade/DistUpgradeViewText.py:140
msgid "A fatal error occurred"
msgstr "Végzetes hiba történt"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:536
msgid ""
"Please report this as a bug (if you haven't already) and include the files /"
"var/log/dist-upgrade/main.log and /var/log/dist-upgrade/apt.log in your "
"report. The upgrade has aborted.\n"
"Your original sources.list was saved in /etc/apt/sources.list.distUpgrade."
msgstr ""
"Jelentse ezt a hibát (ha eddig még nem tette volna) és csatolja a /var/log/"
"dist-upgrade/main.log és /var/log/dist-upgrade/apt.log nevű fájlokat. A "
"frissítés megszakadt. Az eredeti sources.list /etc/apt/sources.list."
"distUpgrade néven került mentésre."

#: ../DistUpgrade/DistUpgradeViewGtk3.py:566
msgid "Ctrl-c pressed"
msgstr "Ctrl+C billentyűkombináció lenyomva"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:567
msgid ""
"This will abort the operation and may leave the system in a broken state. "
"Are you sure you want to do that?"
msgstr ""
"Ez megszakítja a műveletet, és törött állapotban hagyhatja a rendszert. "
"Biztos, hogy ezt akarja tenni?"

#. append warning
#: ../DistUpgrade/DistUpgradeViewGtk3.py:706
msgid "To prevent data loss close all open applications and documents."
msgstr ""
"Az esetleges adatvesztés elkerülése érdekében zárjon be minden nyitott "
"alkalmazást és dokumentumot."

#: ../DistUpgrade/DistUpgradeViewGtk3.py:720
#, python-format
msgid "No longer supported by Canonical (%s)"
msgstr "A Canonical már nem támogatja (%s)"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:721
#, python-format
msgid "<b>Downgrade (%s)</b>"
msgstr "<b>Visszafejlesztendő (%s)</b>"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:722
#, python-format
msgid "Remove (%s)"
msgstr "Eltávolítandó (%s)"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:723
#, python-format
msgid "No longer needed (%s)"
msgstr "Már nem szükséges (%s)"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:724
#, python-format
msgid "Install (%s)"
msgstr "Telepítendő (%s)"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:725
#, python-format
msgid "Upgrade (%s)"
msgstr "Frissítendő (%s)"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:773
msgid "Cancel"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk3.py:774
#: ../DistUpgrade/DistUpgradeViewKDE.py:939
msgid "Continue"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewKDE.py:447
msgid "Show Difference >>>"
msgstr "Különbség megjelenítése >>>"

#: ../DistUpgrade/DistUpgradeViewKDE.py:450
msgid "<<< Hide Difference"
msgstr "<<< Különbség elrejtése"

#: ../DistUpgrade/DistUpgradeViewKDE.py:701
msgid "Error"
msgstr "Hiba"

#: ../DistUpgrade/DistUpgradeViewKDE.py:719
#: ../DistUpgrade/DistUpgradeViewKDE.py:960
msgid "&Close"
msgstr "&Bezárás"

#: ../DistUpgrade/DistUpgradeViewKDE.py:753
msgid "Show Terminal >>>"
msgstr "Terminál megjelenítése >>>"

#: ../DistUpgrade/DistUpgradeViewKDE.py:756
msgid "<<< Hide Terminal"
msgstr "<<< Terminál elrejtése"

#: ../DistUpgrade/DistUpgradeViewKDE.py:829
msgid "Information"
msgstr "Információ"

#: ../DistUpgrade/DistUpgradeViewKDE.py:877
msgid "&Start Upgrade"
msgstr "Frissítés &indítása"

#: ../DistUpgrade/DistUpgradeViewKDE.py:879
#: ../DistUpgrade/DistUpgradeViewKDE.py:923
#: ../DistUpgrade/DistUpgradeViewKDE.py:926
#: ../data/gtkbuilder/DistUpgrade.ui.h:7
msgid "Details"
msgstr "Részletek"

#: ../DistUpgrade/DistUpgradeViewKDE.py:901
#, python-format
msgid "No longer supported %s"
msgstr "Már nem támogatott: %s"

#: ../DistUpgrade/DistUpgradeViewKDE.py:903
#, python-format
msgid "Remove %s"
msgstr "%s eltávolítása"

#: ../DistUpgrade/DistUpgradeViewKDE.py:905
#: ../DistUpgrade/DistUpgradeViewText.py:239
#, python-format
msgid "Remove (was auto installed) %s"
msgstr "%s eltávolítása (automatikusan telepített)"

#: ../DistUpgrade/DistUpgradeViewKDE.py:907
#, python-format
msgid "Install %s"
msgstr "%s telepítése"

#: ../DistUpgrade/DistUpgradeViewKDE.py:909
#, python-format
msgid "Upgrade %s"
msgstr "%s frissítése"

#: ../DistUpgrade/DistUpgradeViewKDE.py:956
#: ../DistUpgrade/DistUpgradeViewText.py:292
msgid "Restart required"
msgstr "Újraindítás szükséges"

#: ../DistUpgrade/DistUpgradeViewKDE.py:956
msgid "<b><big>Restart the system to complete the upgrade</big></b>"
msgstr "<b><big>Indítsa újra a rendszert a frissítés befejezéséhez</big></b>"

#: ../DistUpgrade/DistUpgradeViewKDE.py:959
#: ../data/gtkbuilder/DistUpgrade.ui.h:14
msgid "_Restart Now"
msgstr "Újrain_dítás most"

#. FIXME make this user friendly
#: ../DistUpgrade/DistUpgradeViewKDE.py:977
msgid ""
"<b><big>Cancel the running upgrade?</big></b>\n"
"\n"
"The system could be in an unusable state if you cancel the upgrade. You are "
"strongly advised to resume the upgrade."
msgstr ""
"<b><big>Megszakítja a frissítést?</big></b>\n"
"\n"
"Lehet, hogy a rendszer használhatatlanná válik, ha most megszakítja a "
"frissítést. Erősen ajánlott a frissítés folytatása!"

#: ../DistUpgrade/DistUpgradeViewKDE.py:981
msgid "Cancel Upgrade?"
msgstr "Megszakítja a frissítést?"

#: ../DistUpgrade/DistUpgradeView.py:82
#, python-format
msgid "%li day"
msgid_plural "%li days"
msgstr[0] "%li nap"
msgstr[1] "%li nap"

#: ../DistUpgrade/DistUpgradeView.py:84
#, python-format
msgid "%li hour"
msgid_plural "%li hours"
msgstr[0] "%li óra"
msgstr[1] "%li óra"

#: ../DistUpgrade/DistUpgradeView.py:86
#, python-format
msgid "%li minute"
msgid_plural "%li minutes"
msgstr[0] "%li perc"
msgstr[1] "%li perc"

#: ../DistUpgrade/DistUpgradeView.py:87
#, python-format
msgid "%li second"
msgid_plural "%li seconds"
msgstr[0] "%li másodperc"
msgstr[1] "%li másodperc"

#. TRANSLATORS: you can alter the ordering of the remaining time
#. information here if you shuffle %(str_days)s %(str_hours)s %(str_minutes)s
#. around. Make sure to keep all '$(str_*)s' in the translated string
#. and do NOT change anything appart from the ordering.
#.
#. %(str_hours)s will be either "1 hour" or "2 hours" depending on the
#. plural form
#.
#. Note: most western languages will not need to change this
#: ../DistUpgrade/DistUpgradeView.py:103
#, python-format
msgid "%(str_days)s %(str_hours)s"
msgstr "%(str_days)s %(str_hours)s"

#. TRANSLATORS: you can alter the ordering of the remaining time
#. information here if you shuffle %(str_hours)s %(str_minutes)s
#. around. Make sure to keep all '$(str_*)s' in the translated string
#. and do NOT change anything appart from the ordering.
#.
#. %(str_hours)s will be either "1 hour" or "2 hours" depending on the
#. plural form
#.
#. Note: most western languages will not need to change this
#: ../DistUpgrade/DistUpgradeView.py:121
#, python-format
msgid "%(str_hours)s %(str_minutes)s"
msgstr "%(str_hours)s %(str_minutes)s"

#. 56 kbit
#. 1Mbit = 1024 kbit
#: ../DistUpgrade/DistUpgradeView.py:172
#, python-format
msgid ""
"This download will take about %s with a 1Mbit DSL connection and about %s "
"with a 56k modem."
msgstr ""
"A letöltés körülbelül %s alatt fejeződik be 1 megabites DSL kapcsolaton, és "
"%s alatt 56k-s modem használatával."

#. if we have a estimated speed, use it
#: ../DistUpgrade/DistUpgradeView.py:176
#, python-format
msgid "This download will take about %s with your connection. "
msgstr "A letöltés körülbelül %s alatt fejeződik be ezen a kapcsolaton. "

#. Declare these translatable strings from the .ui files here so that
#. xgettext picks them up.
#: ../DistUpgrade/DistUpgradeView.py:270 ../data/gtkbuilder/DistUpgrade.ui.h:22
msgid "Preparing to upgrade"
msgstr "Felkészülés a frissítésre"

#: ../DistUpgrade/DistUpgradeView.py:271
msgid "Getting new software channels"
msgstr "Új szoftvercsatornák lekérése"

#: ../DistUpgrade/DistUpgradeView.py:272 ../data/gtkbuilder/DistUpgrade.ui.h:24
msgid "Getting new packages"
msgstr "Új csomagok letöltése"

#: ../DistUpgrade/DistUpgradeView.py:273 ../data/gtkbuilder/DistUpgrade.ui.h:27
msgid "Installing the upgrades"
msgstr "A frissítések telepítése"

#: ../DistUpgrade/DistUpgradeView.py:274 ../data/gtkbuilder/DistUpgrade.ui.h:26
msgid "Cleaning up"
msgstr "Frissítés befejezése"

#: ../DistUpgrade/DistUpgradeView.py:363
#, python-format
msgid ""
"%(amount)d installed package is no longer supported by Canonical. You can "
"still get support from the community."
msgid_plural ""
"%(amount)d installed packages are no longer supported by Canonical. You can "
"still get support from the community."
msgstr[0] ""
"%(amount)d szoftvercsomagot a Canonical már nem támogat. A közösségtől "
"továbbra is kaphat támogatást."
msgstr[1] ""
"%(amount)d szoftvercsomagot a Canonical már nem támogat. A közösségtől "
"továbbra is kaphat támogatást."

#. FIXME: make those two separate lines to make it clear
#. that the "%" applies to the result of ngettext
#: ../DistUpgrade/DistUpgradeView.py:372
#, python-format
msgid "%d package is going to be removed."
msgid_plural "%d packages are going to be removed."
msgstr[0] "%d csomag el lesz távolítva."
msgstr[1] "%d csomag el lesz távolítva."

#: ../DistUpgrade/DistUpgradeView.py:377
#, python-format
msgid "%d new package is going to be installed."
msgid_plural "%d new packages are going to be installed."
msgstr[0] "%d új csomag lesz telepítve."
msgstr[1] "%d új csomag lesz telepítve."

#: ../DistUpgrade/DistUpgradeView.py:383
#, python-format
msgid "%d package is going to be upgraded."
msgid_plural "%d packages are going to be upgraded."
msgstr[0] "%d csomag lesz frissítve."
msgstr[1] "%d csomag lesz frissítve."

#: ../DistUpgrade/DistUpgradeView.py:391
#, python-format
msgid ""
"\n"
"\n"
"You have to download a total of %s. "
msgstr ""
"\n"
"\n"
"Összes letöltendő adatmennyiség: %s. "

#: ../DistUpgrade/DistUpgradeView.py:396
msgid ""
"Installing the upgrade can take several hours. Once the download has "
"finished, the process cannot be canceled."
msgstr ""
"A frissítések telepítése órákat vehet igénybe. Ha a letöltés befejeződött, a "
"folyamat már nem állítható meg."

#: ../DistUpgrade/DistUpgradeView.py:400
msgid ""
"Fetching and installing the upgrade can take several hours. Once the "
"download has finished, the process cannot be canceled."
msgstr ""
"A frissítések letöltése és telepítése órákat vehet igénybe. Ha a letöltés "
"befejeződött, a folyamat már nem állítható meg."

#: ../DistUpgrade/DistUpgradeView.py:405
msgid "Removing the packages can take several hours. "
msgstr "A csomagok eltávolítása órákig is eltarthat. "

#. FIXME: this should go into DistUpgradeController
#: ../DistUpgrade/DistUpgradeView.py:410
msgid "The software on this computer is up to date."
msgstr "A szoftverek a számítógépen naprakészek."

#: ../DistUpgrade/DistUpgradeView.py:411
msgid ""
"There are no upgrades available for your system. The upgrade will now be "
"canceled."
msgstr ""
"Nem állnak rendelkezésre frissítések a rendszeréhez. A frissítés most "
"megszakad."

#: ../DistUpgrade/DistUpgradeView.py:427
msgid "Reboot required"
msgstr "Újraindítás szükséges"

#: ../DistUpgrade/DistUpgradeView.py:428
msgid ""
"The upgrade is finished and a reboot is required. Do you want to do this now?"
msgstr ""
"A frissítés elkészült, de a befejezéshez újra kell indítani a rendszert. "
"Újraindítja most?"

#: ../DistUpgrade/DistUpgradeViewText.py:82
#, python-format
msgid "Progress: [%3i%%]"
msgstr "Folyamat: [%3i%%]"

#: ../DistUpgrade/DistUpgradeViewText.py:141
msgid ""
"Please report this as a bug and include the files /var/log/dist-upgrade/main."
"log and /var/log/dist-upgrade/apt.log in your report. The upgrade has "
"aborted.\n"
"Your original sources.list was saved in /etc/apt/sources.list.distUpgrade."
msgstr ""
"Jelentse ezt hibaként és a hibajelentéshez mellékelje a /var/log/dist-"
"upgrade/main.log és /var/log/dist-upgrade/apt.log fájlokat. A frissítés "
"megszakadt. Az eredeti sources.list /etc/apt/sources.list.distUpgrade néven "
"került mentésre."

#: ../DistUpgrade/DistUpgradeViewText.py:165
msgid "Aborting"
msgstr "Megszakítás"

#: ../DistUpgrade/DistUpgradeViewText.py:171
msgid "Demoted:\n"
msgstr "Lefokozott:\n"

#: ../DistUpgrade/DistUpgradeViewText.py:178
msgid "To continue please press [ENTER]"
msgstr "A folytatáshoz nyomja meg az [ENTER] billentyűt"

#: ../DistUpgrade/DistUpgradeViewText.py:215
#: ../DistUpgrade/DistUpgradeViewText.py:253
#: ../DistUpgrade/DistUpgradeViewText.py:261
msgid "Continue [yN] "
msgstr "Folytatja? [i/N] "

#: ../DistUpgrade/DistUpgradeViewText.py:215
#: ../DistUpgrade/DistUpgradeViewText.py:253
msgid "Details [d]"
msgstr "Részletek [r]"

#. TRANSLATORS: the "y" is "yes"
#. TRANSLATORS: first letter of a positive (yes) answer
#: ../DistUpgrade/DistUpgradeViewText.py:219
#: ../DistUpgrade/DistUpgradeViewText.py:264
msgid "y"
msgstr "i"

#. TRANSLATORS: the "n" is "no"
#. TRANSLATORS: first letter of a negative (no) answer
#: ../DistUpgrade/DistUpgradeViewText.py:222
#: ../DistUpgrade/DistUpgradeViewText.py:271
msgid "n"
msgstr "n"

#. TRANSLATORS: the "d" is "details"
#: ../DistUpgrade/DistUpgradeViewText.py:225
msgid "d"
msgstr "r"

#: ../DistUpgrade/DistUpgradeViewText.py:230
#, python-format
msgid "No longer supported: %s\n"
msgstr "Már nem támogatott: %s\n"

#: ../DistUpgrade/DistUpgradeViewText.py:235
#, python-format
msgid "Remove: %s\n"
msgstr "Eltávolítandó: %s\n"

#: ../DistUpgrade/DistUpgradeViewText.py:245
#, python-format
msgid "Install: %s\n"
msgstr "Telepítendő: %s\n"

#: ../DistUpgrade/DistUpgradeViewText.py:250
#, python-format
msgid "Upgrade: %s\n"
msgstr "Frissítendő: %s\n"

#: ../DistUpgrade/DistUpgradeViewText.py:268
msgid "Continue [Yn] "
msgstr "Folytatja? [I/n] "

#: ../DistUpgrade/DistUpgradeViewText.py:293
msgid ""
"To finish the upgrade, a restart is required.\n"
"If you select 'y' the system will be restarted."
msgstr ""
"A frissítés befejezéséhez a rendszer újraindítása szükséges. \n"
"Az „i” választása esetén a rendszer újraindul."

#: ../DistUpgrade/GtkProgress.py:71
#, python-format
msgid "Downloading file %(current)li of %(total)li with %(speed)s/s"
msgstr ""
"%(current)li. fájl letöltése, összesen: %(total)li, sebesség: %(speed)s/s"

#: ../DistUpgrade/GtkProgress.py:77
#, python-format
msgid "Downloading file %(current)li of %(total)li"
msgstr "%(current)li. fájl letöltése, összesen: %(total)li"

#: ../data/gtkbuilder/AcquireProgress.ui.h:1
#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:7
msgid "Show progress of individual files"
msgstr "Egyes fájlok állapotának mutatása"

#: ../data/gtkbuilder/DistUpgrade.ui.h:1
msgid "_Cancel Upgrade"
msgstr "Frissítés _megszakítása"

#: ../data/gtkbuilder/DistUpgrade.ui.h:2
msgid "_Resume Upgrade"
msgstr "Frissítés _folytatása"

#: ../data/gtkbuilder/DistUpgrade.ui.h:3
msgid ""
"<b><big>Cancel the running upgrade?</big></b>\n"
"\n"
"The system could be in an unusable state if you cancel the upgrade. You are "
"strongly adviced to resume the upgrade."
msgstr ""
"<b><big>Megszakítja a folyamatban lévő frissítést?</big></b>\n"
"\n"
"A rendszer használhatatlan állapotban maradhat, ha megszakítja a frissítést. "
"Erősen javasoljuk, hogy folytassa a frissítést."

#: ../data/gtkbuilder/DistUpgrade.ui.h:6
msgid "_Start Upgrade"
msgstr "Frissítés _indítása"

#: ../data/gtkbuilder/DistUpgrade.ui.h:9
msgid "_Replace"
msgstr "_Csere"

#: ../data/gtkbuilder/DistUpgrade.ui.h:10
msgid "Difference between the files"
msgstr "Fájlok közti különbség"

#: ../data/gtkbuilder/DistUpgrade.ui.h:11
msgid "_Report Bug"
msgstr "_Hibabejelentés"

#: ../data/gtkbuilder/DistUpgrade.ui.h:12
msgid "_Continue"
msgstr "_Folytatás"

#: ../data/gtkbuilder/DistUpgrade.ui.h:13
msgid "<b><big>Start the upgrade?</big></b>"
msgstr "<b><big>Megkezdi a frissítést?</big></b>"

#: ../data/gtkbuilder/DistUpgrade.ui.h:15
msgid ""
"<b><big>Restart the system to complete the upgrade</big></b>\n"
"\n"
"Please save your work before continuing."
msgstr ""
"<b><big>A frissítés befejezéséhez újraindítás szükséges</big></b>\n"
"\n"
"Kérem, mentse el munkáját mielőtt folytatná!"

#: ../data/gtkbuilder/DistUpgrade.ui.h:18
msgid "Distribution Upgrade"
msgstr "Disztribúciófrissítés"

#: ../data/gtkbuilder/DistUpgrade.ui.h:20
#, no-c-format
msgid "<b><big>Upgrading Ubuntu to version %s</big></b>"
msgstr "<b><big>Ubuntu frissítése a %s-es verzióra</big></b>"

#: ../data/gtkbuilder/DistUpgrade.ui.h:21
msgid "    "
msgstr "    "

#: ../data/gtkbuilder/DistUpgrade.ui.h:23
msgid "Setting new software channels"
msgstr "Új szoftvercsatornák beállítása"

#: ../data/gtkbuilder/DistUpgrade.ui.h:25
msgid "Restarting the computer"
msgstr "A számítógép újraindítása"

#: ../data/gtkbuilder/DistUpgrade.ui.h:28
msgid "Terminal"
msgstr "Terminál"

#: ../data/gtkbuilder/ReleaseNotes.ui.h:2
msgid "_Upgrade"
msgstr "_Frissítés"

#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:1
msgid "<b>A new version of Ubuntu is available. Would you like to upgrade?</b>"
msgstr "<b>Elérhető az Ubuntu egy új változata. Szeretné frissíteni?</b>"

#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:2
msgid "Don't Upgrade"
msgstr "Ne frissítse"

#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:3
msgid "Ask Me Later"
msgstr "Kérdezzen rá később"

#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:4
msgid "Yes, Upgrade Now"
msgstr "Igen, frissítse most"

#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:5
msgid "You have declined to upgrade to the new Ubuntu"
msgstr "Ön elutasította az Ubuntu új változatára történő frissítést."

#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:6
msgid ""
"You can upgrade at a later time by opening Software Updater and click on "
"\"Upgrade\"."
msgstr ""
"Később is frissíthet a Frissítéskezelő megnyitásával, majd a „Frissítés” "
"gombra kattintva."

#: ../data/com.ubuntu.release-upgrader.policy.in.h:1
msgid "Perform a release upgrade"
msgstr "Kiadásfrissítés végrehajtása"

#: ../data/com.ubuntu.release-upgrader.policy.in.h:2
msgid "To upgrade Ubuntu, you need to authenticate."
msgstr "A frissítéshez hitelesítés szükséges."

#: ../data/com.ubuntu.release-upgrader.policy.in.h:3
msgid "Perform a partial upgrade"
msgstr "Részleges frissítés végrehajtása"

#: ../data/com.ubuntu.release-upgrader.policy.in.h:4
msgid "To perform a partial upgrade, you need to authenticate."
msgstr "Részleges frissítés elvégzéséhez hitelesítés szükséges."

#: ../do-partial-upgrade:75 ../do-release-upgrade:80
msgid "Show version and exit"
msgstr "Verziószám kiírása és kilépés"

#: ../do-partial-upgrade:78 ../do-release-upgrade:87
msgid "Directory that contains the data files"
msgstr "Az adatfájlokat tartalmazó könyvtár"

#: ../do-partial-upgrade:81 ../do-release-upgrade:100
msgid "Run the specified frontend"
msgstr "A megadott előtét futtatása"

#: ../do-partial-upgrade:112
msgid "Running partial upgrade"
msgstr "Intelligens frissítés futtatása"

#: ../do-release-upgrade:34 ../do-release-upgrade:46
msgid "Downloading the release upgrade tool"
msgstr "A kiadásfrissítő eszköz letöltése"

#: ../do-release-upgrade:83
msgid ""
"If using the latest supported release, upgrade to the development release"
msgstr "Legfrissebb verzió használata esetén, a fejlesztői kiadásra frissítsen"

#: ../do-release-upgrade:90 ../check_new_release_gtk.py:181
msgid ""
"Try upgrading to the latest release using the upgrader from $distro-proposed"
msgstr ""
"Kísérlet a legfrissebb kiadásra való áttérésre $distro-proposed kiadásról a "
"frissítő használatával"

#: ../do-release-upgrade:94
msgid ""
"Run in a special upgrade mode.\n"
"Currently 'desktop' for regular upgrades of a desktop system and 'server' "
"for server systems are supported."
msgstr ""
"Futtatás speciális frissítő módban.\n"
"Jelenleg a „desktop” (asztali rendszerek szabályos frissítése) és a "
"„server” (kiszolgálórendszerek frissítése) módok támogatottak."

#: ../do-release-upgrade:103
msgid ""
"Check only if a new distribution release is available and report the result "
"via the exit code"
msgstr ""
"Csak akkor ellenőrizze, ha egy új kiadás elérhetővé válik, az eredményt "
"jelenítse meg a kimeneti értékben"

#: ../do-release-upgrade:108
msgid ""
"Try the upgrade with third party mirrors and repositories enabled instead of "
"commenting them out."
msgstr ""

#: ../do-release-upgrade:122
msgid "The options --devel-release and --proposed are"
msgstr "A --devel-release és --proposed kapcsolók"

#: ../do-release-upgrade:123
msgid "mutually exclusive. Please use only one of them."
msgstr "kölcsönösen kizárják egymást. Csak az egyiket használja."

#: ../do-release-upgrade:127
msgid "Checking for a new Ubuntu release"
msgstr "Új Ubuntu kiadás keresése"

#: ../do-release-upgrade:139
msgid "Your Ubuntu release is not supported anymore."
msgstr "Az Ön Ubuntu kiadása már nem támogatott."

#: ../do-release-upgrade:140
msgid ""
"For upgrade information, please visit:\n"
"%(url)s\n"
msgstr ""
"Frissítési információkért lásd:\n"
"%(url)s\n"

#: ../do-release-upgrade:147
msgid "In /etc/update-manager/release-upgrades Prompt "
msgstr ""

#: ../do-release-upgrade:148
msgid "is set to never so upgrading is not possible."
msgstr ""

#: ../do-release-upgrade:150
msgid "There is no development version of an LTS available."
msgstr ""

#: ../do-release-upgrade:151
msgid "To upgrade to the latest non-LTS development release "
msgstr ""

#: ../do-release-upgrade:152
msgid "set Prompt=normal in /etc/update-manager/release-upgrades."
msgstr ""

#: ../do-release-upgrade:154
msgid "Upgrades to the development release are only "
msgstr "A fejlesztői kiadásra frissítés csak a legfrissebb "

#: ../do-release-upgrade:155
msgid "available from the latest supported release."
msgstr "támogatott verzióról lehetséges."

#: ../do-release-upgrade:157
msgid "No new release found."
msgstr "Nem található újabb kiadás."

#: ../do-release-upgrade:162
msgid "Release upgrade not possible right now"
msgstr "A kiadás frissítése most nem lehetséges"

#: ../do-release-upgrade:163
#, c-format
msgid ""
"The release upgrade can not be performed currently, please try again later. "
"The server reported: '%s'"
msgstr ""
"A kiadás frissítése jelenleg nem hajtható végre, próbálja újra később. A "
"kiszolgáló üzenete: „%s”"

#: ../do-release-upgrade:169
#, c-format
msgid "New release '%s' available."
msgstr "Elérhető az új „%s” kiadás."

#: ../do-release-upgrade:170
msgid "Run 'do-release-upgrade' to upgrade to it."
msgstr "A frissítéshez futassa a „do-release-upgrade” parancsot."

#: ../do-release-upgrade:187
msgid "Please install all available updates for your release before upgrading."
msgstr ""

#: ../do-release-upgrade:203
msgid ""
"You have not rebooted after updating a package which requires a reboot. "
"Please reboot before upgrading."
msgstr ""

#: ../check_new_release_gtk.py:85
msgid "Software Updater"
msgstr "Frissítéskezelő"

#: ../check_new_release_gtk.py:113
#, python-format
msgid "Ubuntu %(version)s Upgrade Available"
msgstr "Ubuntu %(version)s frissítés érhető el"

#. print("don't upgrade")
#: ../check_new_release_gtk.py:144
#, python-format
msgid "You have declined the upgrade to Ubuntu %s"
msgstr "Ön elutasította az Ubuntu %s kiadásra történő frissítést"

#: ../check_new_release_gtk.py:177
msgid "Check if upgrading to the latest devel release is possible"
msgstr "Ellenőrzi, hogy lehetséges-e frissíteni a legújabb fejlesztői kiadásra"

#: ../check_new_release_gtk.py:186
msgid "Add debug output"
msgstr "Hibakeresési kimenet hozzáadása"

#~ msgid ""
#~ "An unresolvable problem occurred while calculating the upgrade:\n"
#~ "%s\n"
#~ "\n"
#~ " This can be caused by:\n"
#~ " * Upgrading to a pre-release version of Ubuntu\n"
#~ " * Running the current pre-release version of Ubuntu\n"
#~ " * Unofficial software packages not provided by Ubuntu\n"
#~ "\n"
#~ msgstr ""
#~ "Megoldhatatlan probléma adódott a frissítés előkészítése közben:\n"
#~ "%s\n"
#~ "\n"
#~ " Ezt az alábbiak okozhatták:\n"
#~ " * frissítés egy kiadás előtti Ubuntu verzióra\n"
#~ " * Ön jelenleg egy kiadás előtti Ubuntu verziót használ\n"
#~ " * az Ubuntu által nem támogatott csomagok\n"
#~ "\n"

#~ msgid ""
#~ "Your system does not contain a ubuntu-desktop, kubuntu-desktop, xubuntu-"
#~ "desktop or edubuntu-desktop package and it was not possible to detect "
#~ "which version of Ubuntu you are running.\n"
#~ " Please install one of the packages above first using synaptic or apt-get "
#~ "before proceeding."
#~ msgstr ""
#~ "A rendszere nem tartalmazza az ubuntu-desktop, kubuntu-desktop, xubuntu-"
#~ "desktop vagy edubuntu-desktop csomagok egyikét sem, és nem lehetett "
#~ "megállapítani, hogy az Ubuntu mely változatát használja.\n"
#~ " A folytatás előtt telepítse a fenti csomagok egyikét a synaptic vagy az "
#~ "apt-get használatával."

#~ msgid "Sandbox setup failed"
#~ msgstr "A tesztkörnyezet beállítása meghiúsult"

#~ msgid "It was not possible to create the sandbox environment."
#~ msgstr "Nem sikerült létrehozni a tesztkörnyezetet."

#~ msgid "Sandbox mode"
#~ msgstr "Teszt mód"

#~ msgid ""
#~ "This upgrade is running in sandbox (test) mode. All changes are written "
#~ "to '%s' and will be lost on the next reboot.\n"
#~ "\n"
#~ "*No* changes written to a system directory from now until the next reboot "
#~ "are permanent."
#~ msgstr ""
#~ "Ez a frissítés sandbox (teszt) módban fut. A(z) „%s” összes változása el "
#~ "fog veszni a következő újraindításnál.\n"
#~ "\n"
#~ "A mostantól a következő újraindításig a rendszerkönyvtárakban történő "
#~ "változások *nem* lesznek állandó érvényűek."

#~ msgid ""
#~ "Your python install is corrupted. Please fix the '/usr/bin/python' "
#~ "symlink."
#~ msgstr ""
#~ "A Python telepítése sérült. Javítsa ki a „/usr/bin/python” szimbolikus "
#~ "linket."

#~ msgid "Package 'debsig-verify' is installed"
#~ msgstr "A „debsig-verify” csomag telepítve van"

#~ msgid ""
#~ "The upgrade can not continue with that package installed.\n"
#~ "Please remove it with synaptic or 'apt-get remove debsig-verify' first "
#~ "and run the upgrade again."
#~ msgstr ""
#~ "A frissítés nem folytatódhat, ha ez a csomag telepítve van.\n"
#~ "Távolítsa el a Synaptic vagy az „apt-get remove debsig-verify” parancs "
#~ "kiadásával és futtassa újra a frissítést."

#~ msgid ""
#~ "While scanning your repository information no mirror entry for the "
#~ "upgrade was found. This can happen if you run a internal mirror or if the "
#~ "mirror information is out of date.\n"
#~ "\n"
#~ "Do you want to rewrite your 'sources.list' file anyway? If you choose "
#~ "'Yes' here it will update all '%s' to '%s' entries.\n"
#~ "If you select 'No' the upgrade will cancel."
#~ msgstr ""
#~ "A tárolóinformációk elemzése során a program nem talált tükörbejegyzést a "
#~ "frissítéshez. Ez akkor fordulhat elő, ha belső tükröt használ, vagy a "
#~ "tükörinformációk elavultak.\n"
#~ "\n"
#~ "Mindenképpen újra kívánja írni a sources.list fájlt? Ha az „Igen” gombot "
#~ "választja, akkor az összes „%s” bejegyzés „%s” bejegyzéssé lesz "
#~ "frissítve. A „Nem” kiválasztása megszakítja a frissítést."

#~ msgid ""
#~ "The upgrade has aborted. The upgrade needs a total of %s free space on "
#~ "disk '%s'. Please free at least an additional %s of disk space on '%s'. "
#~ "Empty your trash and remove temporary packages of former installations "
#~ "using 'sudo apt-get clean'."
#~ msgstr ""
#~ "A frissítés megszakadt. A frissítéshez %s szabad hely szükséges a(z) „%s” "
#~ "lemezen. Szabadítson fel további %s lemezterületet a(z) „%s” eszközön. "
#~ "Ürítse a Kukát és törölje a korábbi telepítések átmeneti fájljait a „sudo "
#~ "apt-get clean” parancs kiadásával."

#~ msgid "evms in use"
#~ msgstr "Az evms használatban van"

#~ msgid ""
#~ "Your system uses the 'evms' volume manager in /proc/mounts. The 'evms' "
#~ "software is no longer supported, please switch it off and run the upgrade "
#~ "again when this is done."
#~ msgstr ""
#~ "A rendszer az „evms” kötetkezelőt használja a /proc/mounts alatt. Az "
#~ "„evms” szoftver már nem támogatott, kapcsolja ki és futtassa újra a "
#~ "frissítést."

#~ msgid ""
#~ "This computer is currently using the NVIDIA 'nvidia' graphics driver. No "
#~ "version of this driver is available that works with your video card in "
#~ "Ubuntu 10.04 LTS.\n"
#~ "\n"
#~ "Do you want to continue?"
#~ msgstr ""
#~ "Ez a számítógép jelenleg az NVIDIA „nvidia” grafikus meghajtóját "
#~ "használja. Ennek a meghajtónak nem érhető el a videokártyáját az Ubuntu "
#~ "10.04 LTS alatt kezelni képes verziója.\n"
#~ "\n"
#~ "Biztosan folytatja?"

#~ msgid "No i686 CPU"
#~ msgstr "Nem i686-os CPU"

#~ msgid ""
#~ "Your system uses an i586 CPU or a CPU that does not have the 'cmov' "
#~ "extension. All packages were built with optimizations requiring i686 as "
#~ "the minimal architecture. It is not possible to upgrade your system to a "
#~ "new Ubuntu release with this hardware."
#~ msgstr ""
#~ "A rendszere i586-os CPU-t, vagy a „cmov” kiterjesztéssel nem rendelkező "
#~ "CPU-t használ. Minden csomag a minimális architektúraként az i686-ot "
#~ "megkövetelő optimalizációkkal készült. Rendszere ezzel a hardverrel nem "
#~ "frissíthető új Ubuntu kiadásra."

#~ msgid "Sandbox upgrade using aufs"
#~ msgstr "Tesztfrissítés aufs használatával"

#~ msgid "Test upgrade with a sandbox aufs overlay"
#~ msgstr "Tesztfrissítés tesztkörnyezetben aufs használatával"

#~ msgid "No new release found"
#~ msgstr "Nem található új kiadás"

#~ msgid "Authentication is required to perform a release upgrade"
#~ msgstr "A kiadásfrissítéshez hitelesítés szükséges"

#~ msgid ""
#~ "If none of this applies, then please report this bug using the command "
#~ "'ubuntu-bug ubuntu-release-upgrader-core' in a terminal."
#~ msgstr ""
#~ "Ha a felsoroltak egyike sem áll fenn, akkor jelentse ezt a hibát a "
#~ "terminálban kiadott „ubuntu-bug ubuntu-release-upgrader-core” paranccsal."

#~ msgid "Authentication is required to perform a partial upgrade"
#~ msgstr "Hitelesítés szükséges a részleges kiadásfrissítéshez"

#~ msgid ""
#~ "An unresolvable problem occurred while calculating the upgrade.\n"
#~ "\n"
#~ " This can be caused by:\n"
#~ " * Upgrading to a pre-release version of Ubuntu\n"
#~ " * Running the current pre-release version of Ubuntu\n"
#~ " * Unofficial software packages not provided by Ubuntu\n"
#~ "\n"
#~ msgstr ""
#~ "Megoldhatatlan probléma jelentkezett a frissítés közben.\n"
#~ "\n"
#~ " Ezt a következők okozhatták:\n"
#~ " * Frissítés az Ubuntu egy kiadás előtti verziójára\n"
#~ " * Az Ubuntu egy kiadás előtti verziójának futtatása\n"
#~ " * Nemhivatalos csomagok, melyeket nem az Ubuntu szolgáltat\n"
#~ "\n"

#~ msgid "<b><big>Upgrading Ubuntu to version 15.04</big></b>"
#~ msgstr "<b><big>Az Ubuntu frissítése a 15.04-es verzióra</big></b>"

#~ msgid "<b><big>Upgrading Ubuntu to version 15.10</big></b>"
#~ msgstr "<b><big>Ubuntu frissítése a 15.10-es verzióra</big></b>"
